demo/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^markitup/', include('markitup.urls')),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^about/', TemplateView.as_view(template_name='demo/about.html')),
    url(r'^', include('solo.urls')),
)

urlpatterns += staticfiles_urlpatterns()

solo/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('solo.views',
    url(r'^add/$', 'add', name='add'),
    url(r'^edit/(?P<slug>[-\w]+)/$', 'edit', name='edit'),
    url(r'^$', 'page', name='home'),
    url(r'^(?P<page_number>\d+)/$', 'page', name='page'),
    url(r'^(?P<slug>[-\w]+)/$', 'detail', name='detail')
)

solo/models.py
from django.db import models
from autoslug import AutoSlugField
from django.db.models.signals import pre_save
from django.dispatch import receiver
import datetime


class Post(models.Model):
    """
    An article or page.
    """
    pubdate = models.DateTimeField(blank=True)  # For ordering
    modified = models.DateTimeField(blank=True, editable=False)  # Last edit
    public = models.BooleanField(default=False)  # Display true/false
    title = models.CharField(max_length=100, blank=True)  # auto-populated from post
    body_markdown = models.TextField(blank=True)
    body_html = models.TextField(blank=True)
    slug = AutoSlugField(populate_from='title', unique=True)

    def set_timestamps(self):
        """
        Because auto_now and auto_now_add don't play nice with admin
        """
        if not (self.id or self.pubdate):
            print "setting pubdate"
            self.pubdate = datetime.datetime.today()
        self.modified = datetime.datetime.now()

    class Meta:
        ordering = ('-pubdate', )


@receiver(pre_save, sender=Post)
def auto_fields(sender, instance, **kwargs):
    instance.set_timestamps()

solo/forms.py
from django.forms import ModelForm
from solo.models import Post


class PostForm(ModelForm):

    readonly_fields = ('modified', )

    class Meta:
        model = Post

solo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from solo.models import Post
from solo.forms import PostForm


def add(request, template_name='solo/edit.html'):
    """
    Create a new post
    """
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save()
        return redirect('edit', slug=post.slug)

    return render(request, template_name, {'form': form})


def edit(request, slug=None, template_name='solo/edit.html'):
    """
    Form view for editing a post.
    """
    post = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        post = form.save()

    return render(request, template_name, {'form': form, 'post': post})


def page(request, page_number=False, slug=False):
    """
    Return a paginated list of articles.
    """
    if slug:
        posts = Post.objects.filter(slug=slug)
        posts_per_page = 1
    else:
        posts = Post.objects.filter(public=True)
        posts_per_page = 10
    paginator = Paginator(posts, posts_per_page)

    try:
        page = int(page_number)
    except ValueError:
        page = 1

    try:
        some_posts = paginator.page(page)
    except (EmptyPage, InvalidPage):
        some_posts = paginator.page(paginator.num_pages)

    return render(request, 'posts.html', {'posts': some_posts})


def detail(request, slug):
    """
    Returns a single article view
    """
    return page(request, 1, slug)

demo/templates/base.html
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>{% block title %}akoumjian.com{% endblock %}</title>
  <link href='http://fonts.googleapis.com/css?family=Lato:400,700,400italic' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}solo/css/solo.css" />
  <link rel="shortcut icon" href="{{ STATIC_URL }}favicon.ico" />
  <link rel="author" href="mailto:akoumjian@gmail.com" />
</head>

<body>
<header>
    <hgroup>
    <h1>akoumjian.com</h1>
    <h2>"Blurbs in space and time."</h2>
    </hgroup>
</header>
<nav>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

demo/templates/demo/about.html
{% extends 'base.html' %}
{% block content %}
<p>The About Page</p>
{% endblock %}

demo/templates/markitup/preview.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>markItUp! preview template (modified)</title>
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}solo/css/style.css" />
</head>
<body>
{{ preview|safe }}
</body>
</html>

solo/templates/base.html
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>{% block title %}akoumjian.com{% endblock %}</title>
  <link href='http://fonts.googleapis.com/css?family=Lato:400,700,400italic' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/style.css" />
  <link rel="shortcut icon" href="{{ STATIC_URL }}favicon.ico" />
  <link rel="author" href="mailto:akoumjian@gmail.com" />
</head>
<body>
  <h1 class="site-header">akoumjian.com</h1>
  <div class="page">
    <nav>
      <ul>
        <li class="blog"><a href="/">Blog</a></li>
        <li class="about"><a href="/about/">About</a></li>
      <ul>
    </nav>
    <section class="content">
    {% block content %}
    {% endblock %}
    </section>
  </div>
</body>
</html>

solo/templates/posts.html
{% extends 'base.html' %}
{% block content %}
{% for post in posts.object_list %}
    <article>
    <header>
        <hgroup>
            <h1><a href="/{{post.slug}}/">{{post.title}}</a></h1>
            <h2>{{post.tagline}}</h2>
            <time datetime="{{post.modified|date:"c"}}" pubdate>{{ post.modified|date:"D d M Y" }}</time>
        </hgroup>
    </header>
    {{post.body_html|safe}}
    </article>
{% endfor %}

<nav>
    <span class="step-links">
        {% if posts.has_previous %}
            <a href="?page={{ posts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">next</a>
        {% endif %}
    </span>
</nav>
{% endblock %}

solo/templates/solo/edit.html
<!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8">

  <title>{{ post.title|default:"New Post"}}</title>
  <link rel="shortcut icon" href="favicon.ico">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/solo.css">
  <!-- <link rel="stylesheet" href="{{ STATIC_URL }}CodeMirror-3.0/lib/codemirror.css"> -->
  <link rel="stylesheet" href="{{ STATIC_URL }}CodeMirror-3.0/theme/monokai.css">
  <link rel="stylesheet" href="{{ STATIC_URL }}highlight.js/styles/monokai.css">
</head>
<body>
  <div class="errors">{{form.errors}}</div>  
  <form action="{% if post %}{% url edit slug=post.slug %}{% else %}{% url add %}{% endif %}" method="post">{% csrf_token %}
    <div class="context">
      <ul>
        {% if post.modified %}<li>Modified: {{ post.modified }}</li>{% endif %}
        <li>{{ form.pubdate.label }}:{{ form.pubdate }}</li>
        <li>{{ form.public.label }}:{{ form.public }}</li>
      </ul>
      <input type="submit" value="save" /> 
      <button id="preview-toggle" type="button">Toggle Preview</button>
    </div>
    <div class="content">
      {{ form.body_markdown }}
      {{ form.body_html.as_hidden }}
      <div class="preview post" id="preview"></div>
    </div>
  </form>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
  <script src="{{ STATIC_URL }}marked-0.2.6/lib/marked.js"></script>
  <script src="{{ STATIC_URL }}CodeMirror-3.0/lib/codemirror.js"></script>
  <script src="{{ STATIC_URL }}CodeMirror-3.0/lib/util/overlay.js"></script>
  <script src="{{ STATIC_URL }}CodeMirror-3.0/mode/markdown/markdown.js"></script>
  <script src="{{ STATIC_URL }}CodeMirror-3.0/mode/gfm/gfm.js"></script>
  <script src="{{ STATIC_URL }}CodeMirror-3.0/mode/python/python.js"></script>
  <script src="{{ STATIC_URL }}highlight.js/highlight.pack.js"></script>
  <script src="{{ STATIC_URL }}js/solo.js"></script>
  <script>
    var solo = Solo({
      'markdown': jQuery("#id_body_markdown")[0],
      'html': jQuery("#id_body_html")[0],
      'preview': jQuery("#preview")[0],
      'toggleButton': jQuery("#preview-toggle")[0]
    });
  </script>

</body>
</html>